gnodeb:
  controlif:
    ip: "tester.my5g.org"
    port: 9487
  dataif:
    ip: "tester.my5g.org"
    port: 2152
  plmnlist:
    mcc: "208"
    mnc: "93"
    tac: "000001"
    gnbid: "000002"
  slicesupportlist:
    sst: "01"
    sd: "010203"
ue:
  msin: "00000001"
  key: "70d49a71dd1a2b806a25abe0ef749f1e"
  opc: "6f1bf53d624b3a43af6592854e2444c7"
  amf: "8000"
  sqn: "0000000"
  hplmn:
    mcc: "208"
    mnc: "93"
  snssai:
    sst: 1
    sd: "010203"
amfif:
  ip: "amf.free5gc.org"
  port: 38412
  name: "free5gc"